redsite/config/routes.rb
Rails.application.routes.draw do
  resources :sensors
  resources :sensors

  root :to => "welcome#index"
  match '/records/append' => 'records#append', via: :post
  match '/records/tail/:sensor_id/:tail' => 'records#tail', via: :get
  match ':controller(/:action(/:id(.:format)))', via: [:get, :post]
end

redsite/app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :sensor
end

redsite/app/models/sensor.rb
class Sensor < ActiveRecord::Base
  enum sensor_type: [:pir, :dht, :flood, :combo]
  SENSOR_TYPES =
    [
       {:value => :pir, :label => "PIR"},
       {:value => :dht, :label => "DHT"},
       {:value => :flood, :label => "FLOOD"},
       {:value => :combo, :label => "COMBO"}
    ]

  has_many :records, dependent: :destroy

  def records_tail
    records[-10,records.length]
  end

end

redsite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

redsite/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :append, only: [:post]
  protect_from_forgery with: :null_session, only: Proc.new { |c| c.request.format.json? }

  def append
    uid = params[:uid]
    txt = params[:txt]

    s = Sensor.where(:uid => "0672FF55-51538850-87123432").take

    if s
      s.records.create(uid: uid, message: txt, time: Time.now)
      render text: "OK:#{uid}<=#{txt}!"
    else
      render text: "ERR:#{uid}=>nil"
    end
  end

  def tail
    sensor_id = params[:sensor_id].to_i
    sensor = (sensor_id && sensor_id != 0) ? Sensor.find(sensor_id) : nil

    unless sensor
      render json: {err: "Sensor not found!", status: :err}
    else
      tail = params[:tail].to_i
      records = sensor.records[(tail == 0) ? -10 : -tail, sensor.records.length]
      render json: {records: records, status: :ok}
    end
  end

end

redsite/app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session, only: Proc.new { |c| c.request.format.json? }

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:uid, :label, :sensor_type)
    end
end

redsite/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @date = Time.now
  end
end

redsite/app/helpers/application_helper.rb
module ApplicationHelper
end

redsite/app/helpers/records_helper.rb
module RecordsHelper
end

redsite/app/helpers/sensors_helper.rb
module SensorsHelper
end

redsite/app/helpers/welcome_helper.rb
module WelcomeHelper
end

redsite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redsite</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <div id="content" class="col-md-12">
      <!--  main content -->

      <%= yield %>

    </div>
  </div>
</div>
</body>
</html>

redsite/app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :sensor_type %><br>
    <%= f.select(:sensor_type, Sensor.sensor_types.keys.map {|t| [t.titleize,t]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

redsite/app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

redsite/app/views/sensors/index.html.erb
<div class="row" ng-app="sensorsApp">

  <%= javascript_include_tag 'sensors' %>

  <div class="col-md-12">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">RS</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#user" style="padding-bottom: 5px; padding-top: 5px" title="Профиль пользователя"><img src="/assets/images/img1.png" style="width: 39px;"></a></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="col-md-10 col-md-push-1">
    <p id="notice"><%= notice %></p>
  </div>
  <div class="col-md-10 col-md-push-1" ui-view>

    <script type="text/ng-template" id="/dash.html">
      <div class="row">
        <div class="list-group col-md-2">
          <a href="#/dash" class="list-group-item active">
            DASHBOARD
          </a>
          <a href="#/pir" class="list-group-item">
            PIR
          </a>
          <a href="#/dht" class="list-group-item">
            DHT
          </a>
          <a href="#/flood" class="list-group-item">
            FLOOD
          </a>
        </div>
        <div class="col-md-10">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">PIR</h4>
            </div>
            <div class="panel-body">
              <div class="btn-group">
                <a class="btn btn-default" href="javascript:void(0);" ng-repeat="sensor in pirs" ng-click="$parent.selected_pir = sensor">{{sensor.label}}</a>
                <!--<a href="javascript:void(0);" ng-click="selected_pir = pirs[0]" class="btn btn-default">{{pirs[0].label}}</a>
                <a href="javascript:void(0);" ng-click="selected_pir = pirs[1]" class="btn btn-default">{{pirs[1].label}}</a>
                <a href="javascript:void(0);" ng-click="selected_pir = pirs[2]" class="btn btn-default">{{pirs[2].label}}</a>
                <a href="javascript:void(0);" ng-click="selected_pir = pirs[3]" class="btn btn-default">{{pirs[3].label}}</a>-->
              </div>
              <div class="row-centered top-buffer">
                <div class="col-md-2 col-centered"><span class="text-center center-block">{{selected_pir.label}}</span></div>
                <div class="col-md-8 col-centered btn-group btn-group-xs" role="group" aria-label="...">
                  <div class="btn btn-default" ng-repeat="rec in selected_pir.records_tail" ng-switch on="rec.message">
                    <span class="glyphicon glyphicon-asterisk text-danger" ng-switch-when="PIR:ON"/>
                    <span class="glyphicon glyphicon-minus text-success" ng-switch-when="PIR:OFF"/>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="panel panel-success">
            <a href="#/add-device" class="btn btn-success"><span class="glyphicon glyphicon-plus"/> Device</a>
          </div>
        </div>
      </div>
    </script>

    <script type="text/ng-template" id="/pir.html">
      <div class="row">
        <div class="list-group col-md-2">
          <a href="#/dash" class="list-group-item">
            DASHBOARD
          </a>
          <a href="#/pir" class="list-group-item active">
            PIR
          </a>
          <a href="#/dht" class="list-group-item">
            DHT
          </a>
          <a href="#/flood" class="list-group-item">
            FLOOD
          </a>
        </div>
        <div class="col-md-10">
          <div class="alert alert-dismissible alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>В разработке!</h4>
          </div>
        </div>
      </div>
    </script>

    <script type="text/ng-template" id="/dht.html">
      <div class="row">
        <div class="list-group col-md-2">
          <a href="#/dash" class="list-group-item">
            DASHBOARD
          </a>
          <a href="#/pir" class="list-group-item">
            PIR
          </a>
          <a href="#/dht" class="list-group-item active">
            DHT
          </a>
          <a href="#/flood" class="list-group-item">
            FLOOD
          </a>
        </div>
        <div class="col-md-10">
          <div class="alert alert-dismissible alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>В разработке!</h4>
          </div>
        </div>
      </div>
    </script>

    <script type="text/ng-template" id="/flood.html">
      <div class="row">
        <div class="list-group col-md-2">
          <a href="#/dash" class="list-group-item">
            DASHBOARD
          </a>
          <a href="#/pir" class="list-group-item">
            PIR
          </a>
          <a href="#/dht" class="list-group-item">
            DHT
          </a>
          <a href="#/flood" class="list-group-item active">
            FLOOD
          </a>
        </div>
        <div class="col-md-10">
          <div class="alert alert-dismissible alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>В разработке!</h4>
          </div>
        </div>
      </div>
    </script>

    <script type="text/ng-template" id="/add-device.html">
      <div class="row">
        <div class="list-group col-md-2">
          <a href="#/dash" class="list-group-item">
            DASHBOARD
          </a>
          <a href="#/pir" class="list-group-item">
            PIR
          </a>
          <a href="#/dht" class="list-group-item">
            DHT
          </a>
          <a href="#/flood" class="list-group-item">
            FLOOD
          </a>
        </div>
        <div class="col-md-10">
          <div class="alert alert-dismissible alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>В разработке!</h4>
          </div>
          <a href="#/dash" class="btn-link">На панель датчиков</a>
        </div>
      </div>
    </script>
  </div>
</div>

redsite/app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

redsite/app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @sensor.uid %>
</p>

<p>
  <strong>Label:</strong>
  <%= @sensor.label %>
</p>

<p>
  <strong>Sensor Type:</strong>
  <%= @sensor.sensor_type %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>

redsite/app/views/welcome/index.html.erb
<div class="row row-centered">
  <div class="col-md-3 col-centered">
    <img src="/assets/images/ban260x260.png" alt="REDSITE"/>

  </div>
</div>
<div class="row row-centered">
  <div class="col-md-5 col-centered">
    <form role="form">
      <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" id="username" name="username" class="form-control" />
      </div>
      <div class="form-group">
        <label for="password">Пароль</label>
        <input type="password" id="password" name="password" class="form-control" />
      </div>

      <input type="submit" value="Вход" />
    </form>
  </div>
</div>
<div class="row row-centered">
  <div class="col-md-3 col-centered">
    <%= link_to 'Пропустить Авторизацию', sensors_path %>
  </div>
</div>